### ISSUE TITLE
default login not working in production

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#109]
Neither in development nor in production build admin login is possible. Default according to readme is "Admin", but the seeders inserts "admin". Both to not work. Maybe the default pwd was changed?
Additionally, in a production build, the seeders seems to fail. After building, I get "No seeders found". 
In development the seeders seem to work (at least no error messages are shown).

**Comment by stylesuxx** [comment]
I double checked and improved the documentation. Now it should be more clear how to get the prod env running.
