### ISSUE TITLE
Model: Taxonomy

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#11]

**Comment by cswertz** [comment]
@stylesuxx Taxonomy entries can not be updated (only the vocable in Taxonomylanguages can - and those can only receive minor changes (typos)). Major changes require a new entry. Thus they are not versioned. Renamed table in ERS to match plural (Taxonomies). Removed createdAt (information is in TaxonomyLanguages).

**Comment by cswertz** [comment]
Kept createdAt still removed versioning

**Comment by cswertz** [comment]
And rootId seems not to be necessary in taxonomies

**Comment by cswertz** [comment]
Sorry - I just discovered that the ERS model did not match migrations. Adjusted the model.
