### ISSUE TITLE
Suggestion: Remove Unique Key from LearningUnits

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#114]
In 00110-LearningUnits there is

unique: 'learningUnitsRootIdCreatedAt',

Actually RootsId does not exist. Additionally, the key does not seem to make sense. Maybe something left from an older ERM-model. I'd suggest to delete that key.

**Comment by stylesuxx** [comment]
Yes, that can be deleted.

**Comment by cswertz** [comment]
done.
