### ISSUE TITLE
Production Build Procedure Problems

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#120]
Creating a production build fails without a prior yarn install, which is neither run by the build script nor mentioned in the instructions. I would like to suggest to add this to the script (better in the long term). Additionally admin login is not working. It seems that the seeders are not run by the build script.

**Comment by stylesuxx** [comment]
To build the prod build, the dependencies for both, client and server need to be installed. Technically we should be able to do this in the build step, but since the prod build is made from a running development setup, I am not sure if this makes sense or if we should just mention in the README that the dependencies need to be installed in both cases.

I can not  see an issue with the admin login on my side - could you post the config you use for the database when running the production build please?

**Comment by stylesuxx** [comment]
Add a script to the root of the project which installs the dependencies for both, client and server, builds the client and moves it to the proper directory in the server. This allows for easy installation.

**Comment by cswertz** [comment]
Hm. Not working here. Output:

info: Listening on port: 3000
(node:10983) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
Error: ENOENT: no such file or directory, stat '/home/cswertz/forschung/projects/1998_lerndorf/data/test/server/build/index.html'

The last error shows up after the first call from the browser and is displayed in the browser too.

**Comment by stylesuxx** [comment]
Could you tell me which steps you took exactly?

**Comment by cswertz** [comment]
git pull
cp /server/server/config/config.example.json /server/server/config/config.json
./build.sh
yarn start

**Comment by stylesuxx** [comment]
Can you please post the whole output from `yarn build` and `yarn start` - I can not reproduce it on my end. With your setup it seems he is looking for the index.html in a wrong folder...

**Comment by cswertz** [comment]
It copies everything do /forschung/projects/1998_lerndorf/data/test/server/server/public/build
I replaced
cp -r build/ ../server/server/public
with
cp -r build/* ../server/server/public/
which did the job. Should I change the script accordingly?

**Comment by cswertz** [comment]
System is running, but login not possible. Maybe seeders are missing?

**Comment by stylesuxx** [comment]
> It copies everything do /forschung/projects/1998_lerndorf/data/test/server/server/public/build
> I replaced
> cp -r build/ ../server/server/public
> with
> cp -r build/* ../server/server/public/
> which did the job. Should I change the script accordingly?

Ah, yes - sorry. I forgot to push that.

**Comment by stylesuxx** [comment]
> System is running, but login not possible. Maybe seeders are missing?

You should see the seeders running when initially starting the server.

**Comment by stylesuxx** [comment]
Can you please check that you have a database in the server dir after starting prod. With default settings it should be called production.sqlite I use sqlitebrowser to inspect the databases. If it exists, you could check if it has been seeded properly.

**Comment by cswertz** [comment]
There's only development.sqlite which was seeded correctly. Output is:

cswertz@cswertz-desktop-arbeitszimmer:~/forschung/projects/1998_lerndorf/data/test/server$ yarn start
yarn run v1.16.0
$ sequelize db:migrate && sequelize db:seed:all && rm -rf ./build && webpack --config webpack.config.server.js

Sequelize CLI [Node: 12.16.2, CLI: 6.2.0, ORM: 6.3.4]

Loaded configuration file "server/config/babelHook.js".
Using environment "development".
(node:11750) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
== 00010-Roles: migrating =======
== 00010-Roles: migrated (0.029s)

== 00015-Taxonomies: migrating =======
== 00015-Taxonomies: migrated (0.007s)

== 00020-Users: migrating =======
== 00020-Users: migrated (0.008s)

== 00030-UserRole: migrating =======
== 00030-UserRole: migrated (0.006s)

== 00040-Capabilities: migrating =======
== 00040-Capabilities: migrated (0.007s)

== 00050-RoleCapability: migrating =======
== 00050-RoleCapability: migrated (0.006s)

== 00060-Languages: migrating =======
== 00060-Languages: migrated (0.006s)

== 00065-CapabilityLanguage: migrating =======
== 00065-CapabilityLanguage: migrated (0.007s)

== 00067-RoleLanguage: migrating =======
== 00067-RoleLanguage: migrated (0.006s)

== 00070-UserLanguage: migrating =======
== 00070-UserLanguage: migrated (0.006s)

== 00080-Files: migrating =======
== 00080-Files: migrated (0.006s)

== 00100-TaxonomyLanguage: migrating =======
== 00100-TaxonomyLanguage: migrated (0.006s)

== 00110-LearningUnits: migrating =======
== 00110-LearningUnits: migrated (0.006s)

== 00120-LearningUnitLanguage: migrating =======
== 00120-LearningUnitLanguage: migrated (0.019s)

== 00130-LearningUnitRelation: migrating =======
== 00130-LearningUnitRelation: migrated (0.006s)

== 00140-KnowledgeUnits: migrating =======
== 00140-KnowledgeUnits: migrated (0.007s)

== 00150-KnowledgeUnitUser: migrating =======
== 00150-KnowledgeUnitUser: migrated (0.006s)

== 00160-LearningUnitTag: migrating =======
== 00160-LearningUnitTag: migrated (0.007s)

== 00170-KnowledgeUnitUserRating: migrating =======
== 00170-KnowledgeUnitUserRating: migrated (0.007s)

== 00180-KnowledgeUnitUserLog: migrating =======
== 00180-KnowledgeUnitUserLog: migrated (0.006s)

== 00190-Texts: migrating =======
== 00190-Texts: migrated (0.007s)

== 00200-TextFile: migrating =======
== 00200-TextFile: migrated (0.006s)

== 00210-LogUser: migrating =======
== 00210-LogUser: migrated (0.009s)

== 00300-Courses: migrating =======
== 00300-Courses: migrated (0.007s)

== 00310-CourseUser: migrating =======
== 00310-CourseUser: migrated (0.006s)

== 00320-CourseContent: migrating =======
== 00320-CourseContent: migrated (0.006s)

== 00330-CourseSequence: migrating =======
== 00330-CourseSequence: migrated (0.007s)

== 00340-CourseSequenceKnowledgeUnit: migrating =======
== 00340-CourseSequenceKnowledgeUnit: migrated (0.007s)

== 00350-CourseUserLog: migrating =======
== 00350-CourseUserLog: migrated (0.006s)


Sequelize CLI [Node: 12.16.2, CLI: 6.2.0, ORM: 6.3.4]

Loaded configuration file "server/config/babelHook.js".
Using environment "development".
(node:11762) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
== 00010-Roles: migrating =======
== 00010-Roles: migrated (0.112s)

== 00020-Users: migrating =======
== 00020-Users: migrated (0.007s)

== 00030-UserRole: migrating =======
== 00030-UserRole: migrated (0.009s)

== 00040-Capabilities: migrating =======
== 00040-Capabilities: migrated (0.008s)

== 00050-RoleCapability: migrating =======
== 00050-RoleCapability: migrated (0.031s)

== 00060-Languages: migrating =======
== 00060-Languages: migrated (0.007s)

== 00065-CapabilityLanguage: migrating =======
== 00065-CapabilityLanguage: migrated (0.073s)

== 00067-RoleLanguage: migrating =======
== 00067-RoleLanguage: migrated (0.016s)

== 00070-UserLanguage: migrating =======
== 00070-UserLanguage: migrated (0.008s)

== 00080-Files: migrating =======
== 00080-Files: migrated (0.006s)

== 00090-Taxonomies: migrating =======
== 00090-Taxonomies: migrated (0.008s)

== 00100-TaxonomyLanguage: migrating =======
== 00100-TaxonomyLanguage: migrated (0.206s)

== 00110-LearningUnits: migrating =======
== 00110-LearningUnits: migrated (0.008s)

== 00120-LearningUnitLanguage: migrating =======
== 00120-LearningUnitLanguage: migrated (0.007s)

== 00130-LearningUnitRelation: migrating =======
== 00130-LearningUnitRelation: migrated (0.007s)

== 00140-KnowledgeUnits: migrating =======
== 00140-KnowledgeUnits: migrated (0.006s)

== 00150-KnowledgeUnitUser: migrating =======
== 00150-KnowledgeUnitUser: migrated (0.007s)

== 00160-LearningUnitTag: migrating =======
== 00160-LearningUnitTag: migrated (0.006s)

== 00170-KnowledgeUnitUserRating: migrating =======
== 00170-KnowledgeUnitUserRating: migrated (0.006s)

== 00180-KnowledgeUnitUserLog: migrating =======
== 00180-KnowledgeUnitUserLog: migrated (0.007s)

== 00190-Texts: migrating =======
== 00190-Texts: migrated (0.006s)

== 00200-TextFile: migrating =======
== 00200-TextFile: migrated (0.006s)

== 00210-LogUser: migrating =======
== 00210-LogUser: migrated (0.006s)


webpack is watching the files…

Hash: 8f132c1d779e0f09021c
Version: webpack 4.44.1
Time: 883ms
Built at: 2020-11-24 10:52:53
    Asset     Size  Chunks             Chunk Names
server.js  177 KiB    main  [emitted]  main
Entrypoint main = server.js
[0] multi webpack/hot/poll?1000 ./server/index 40 bytes {main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.34 KiB {main} [built]
[./node_modules/webpack/hot/poll.js?1000] (webpack)/hot/poll.js?1000 1.12 KiB {main} [built]
[./server/config/config.json] 1.5 KiB {main} [built]
[./server/config/passport.js] 3.35 KiB {main} [built]
[./server/config/routes.js] 965 bytes {main} [built]
[./server/index.js] 639 bytes {main} [built]
[./server/logger.js] 500 bytes {main} [built]
[./server/server.js] 1.39 KiB {main} [built]
[body-parser] external "body-parser" 42 bytes {main} [built]
[express] external "express" 42 bytes {main} [built]
[express-fileupload] external "express-fileupload" 42 bytes {main} [built]
[express-session] external "express-session" 42 bytes {main} [built]
[http] external "http" 42 bytes {main} [built]
    + 39 hidden modules
/
info: Listening on port: 3000
(node:11786) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
Executing (default): SELECT `User`.`id`, `User`.`username`, `User`.`password`, `User`.`preferredLanguage`, `User`.`titlePrefix`, `User`.`titleSuffix`, `User`.`description`, `User`.`firstName`, `User`.`birthdate`, `User`.`lastName`, `User`.`studyId`, `User`.`country`, `User`.`website`, `User`.`picture`, `User`.`street`, `User`.`email`, `User`.`phone`, `User`.`city`, `User`.`zip`, `Languages`.`id` AS `Languages.id`, `Languages`.`code` AS `Languages.code`, `Languages`.`name` AS `Languages.name`, `Languages`.`createdAt` AS `Languages.createdAt`, `Languages`.`updatedAt` AS `Languages.updatedAt`, `Languages->UserLanguage`.`id` AS `Languages.UserLanguage.id`, `Languages->UserLanguage`.`UserId` AS `Languages.UserLanguage.UserId`, `Languages->UserLanguage`.`LanguageId` AS `Languages.UserLanguage.LanguageId`, `Languages->UserLanguage`.`level` AS `Languages.UserLanguage.level`, `Languages->UserLanguage`.`createdAt` AS `Languages.UserLanguage.createdAt`, `Languages->UserLanguage`.`updatedAt` AS `Languages.UserLanguage.updatedAt` FROM `Users` AS `User` LEFT OUTER JOIN `UserLanguage` AS `Languages->UserLanguage` ON `User`.`id` = `Languages->UserLanguage`.`UserId` LEFT OUTER JOIN `Languages` AS `Languages` ON `Languages`.`id` = `Languages->UserLanguage`.`LanguageId` WHERE `User`.`username` = 'admin' AND `User`.`active` = 1;
Executing (default): SELECT `User`.`id`, `User`.`username`, `User`.`password`, `User`.`preferredLanguage`, `User`.`titlePrefix`, `User`.`titleSuffix`, `User`.`description`, `User`.`firstName`, `User`.`birthdate`, `User`.`lastName`, `User`.`studyId`, `User`.`country`, `User`.`website`, `User`.`picture`, `User`.`street`, `User`.`email`, `User`.`phone`, `User`.`city`, `User`.`zip`, `Languages`.`id` AS `Languages.id`, `Languages`.`code` AS `Languages.code`, `Languages`.`name` AS `Languages.name`, `Languages`.`createdAt` AS `Languages.createdAt`, `Languages`.`updatedAt` AS `Languages.updatedAt`, `Languages->UserLanguage`.`id` AS `Languages.UserLanguage.id`, `Languages->UserLanguage`.`UserId` AS `Languages.UserLanguage.UserId`, `Languages->UserLanguage`.`LanguageId` AS `Languages.UserLanguage.LanguageId`, `Languages->UserLanguage`.`level` AS `Languages.UserLanguage.level`, `Languages->UserLanguage`.`createdAt` AS `Languages.UserLanguage.createdAt`, `Languages->UserLanguage`.`updatedAt` AS `Languages.UserLanguage.updatedAt` FROM `Users` AS `User` LEFT OUTER JOIN `UserLanguage` AS `Languages->UserLanguage` ON `User`.`id` = `Languages->UserLanguage`.`UserId` LEFT OUTER JOIN `Languages` AS `Languages` ON `Languages`.`id` = `Languages->UserLanguage`.`LanguageId` WHERE `User`.`username` = 'admin' AND `User`.`active` = 1;

**Comment by stylesuxx** [comment]
@cswertz we can close this one now, no?

**Comment by cswertz** [comment]
Yes indeed.
