### ISSUE TITLE
Add Knowledge Unit: LU title missing, numbers not recognized

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#122]
- When adding a knowledge unit the title of the learning unit is not shown (I assume it should show up between the "")
- When calling the entry form the first time, it is possible to enter text in the recommended age field. This is dropped when saving without further notice. After leaving the field and entering the field again (without saving) it is not possible to enter text (only numbers).
- It is possible to add text into the "time in minutes" field.

**Comment by stylesuxx** [comment]
- [ ] Time in minutes should be a number field
- [ ] Recommended age field is not saved
- [ ] Title of LU not shown when adding KU

**Comment by stylesuxx** [comment]
@cswertz Unfortunately there is not much I can do against the text in number fields - this is a Problem with firefox, it simply allows any input in number fields. Further it does not trigger a change event when letters are input into the number field, so I can't really catch this.

I can only react once the input loses focus (which is what is happening...)

**Comment by stylesuxx** [comment]
@cswertz I can also not reproduce the title not being shown. Could it be, that this happened after deleting the language, and thus the titles for the learning units?

**Comment by cswertz** [comment]
Yes. No it works fine. THX!
