### ISSUE TITLE
Deleting a language seems not to work

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#125]
Deleting a language is kind of problematic and not working. As far as I see the idea is that all entries connected to the language are deleted, which makes sense. But I strongly suggest a warning that states exactly that before actually deleting a language. Additionally, the language is not really deleted (or the database is not configured properly). At least, content and the label is still there, while the database entry is missing: 

![Bildschirmfoto vom 2020-11-23 10-38-35](https://user-images.githubusercontent.com/15083008/99947326-1d8c6e00-2d78-11eb-8d94-cf9ee75da83b.png)

I can add foreign keys (and maybe some validations and indexes) - but according to this:
https://sequelize.org/master/class/lib/associations/base.js~Association.html
cascade is not used on deletion. Forum entries vary (at least it can be declared). Assume we have to test it...

**Comment by stylesuxx** [comment]
- [ ] Do not allow languages to be deleted unless it has not been used yet.
