### ISSUE TITLE
Logic for displaying LU's

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#129]
- [ ] If the user is not logged in, only relations to LUs with KUs that are visible for the public should be shown.
- [ ] If the user is logged in, only relations to LUs with KUs that are marked as lectored or owned by the user should be shown. 
- [ ] If the user is in a coursse, only relations to LUs with KUs in the course (no matter if visible to the public in a public course ore lectored) should be shown.

**Comment by cswertz** [comment]
Moved to new features
