### ISSUE TITLE
Model: Knowledgeunit

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#13]
### Renamed:
* mediatype -> mediaType
* knowledgetype -> knowledgeType
* objecttype -> objectType
* eqflevel -> eqfLevel
* courselevel -> courseLevel
* suitableblind -> suitableBlind
* suitabledeaf -> suitableDeaf
* suitabledumb -> suitableDumb
* visiblepublic -> visiblePublic
* visiblelexicon -> visibleLexicon
* visiblecourses -> visibleCourses
* learningtime -> time
* learningobjectives -> objective
* recommendedage -> recommendedAge

**Comment by stylesuxx** [comment]
@cswertz This model has a field *minimumscreenresolution* which is an int. Maybe this should be a text so one could write a proper resolution like *1024x768 pixel* - or what is this field for exactly?

**Comment by cswertz** [comment]
I read a bit about different ways to express screen resolutions. That seems to be a heterogeneous issue. I thought that something like 480, 576, 760 etc. would be easy. But since this is not clear yet, a text field is certainly more flexible. Thus: OK for me - thank's!

**Comment by stylesuxx** [comment]
Taxonomy is a good idea for screen resolution.

How about the learningtime - integer and minutes is OK?

**Comment by cswertz** [comment]
> How about the learningtime - integer and minutes is OK?
>
>
Yes, perfect. thank's!

Grüße

Christian Swertz

http://medienpaedagogik.univie.ac.at/
http://www.medienimpulse.at
http://www.swertz.at
+43.1.4277.46741
