### ISSUE TITLE
Bug in Client

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#143]
home/cswertz/forschung/projects/1998_lerndorf/data/test/client/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

[Error: ENOENT: no such file or directory, stat '/initrd.img'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/initrd.img'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by stylesuxx** [comment]
can you pleas re-run module installation in the client and try again?

**Comment by cswertz** [comment]
Works. Thx!
