### ISSUE TITLE
Fehler bei zweiter Relation zwischen Lerneinheiten - vermutlich Seederproblem

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#152]
TypeError: linkText[0] is undefined
buildRelations/elements<
src/components/learningUnits/Show.jsx:46

  43 | elements = relations.map((item) => {
  44 |   const taxonomyTerm = term(item.Taxonomy, languageId);
  45 |   let linkText = item.target.Translations.filter((item) => item.LanguageId === languageId);
> 46 |   linkText = linkText[0].title;
     | ^  47 | 
  48 |   return (
  49 |     <li>

buildRelations
src/components/learningUnits/Show.jsx:43

  40 | const buildRelations = (relations) => {
  41 |   let elements = null;
  42 |   if (relations.length > 0) {
> 43 |     elements = relations.map((item) => {
     | ^  44 |       const taxonomyTerm = term(item.Taxonomy, languageId);
  45 |       let linkText = item.target.Translations.filter((item) => item.LanguageId === languageId);
  46 |       linkText = linkText[0].title;

LearningUnitsShow
src/components/learningUnits/Show.jsx:58

  55 | 
  56 |   return elements;
  57 | };
> 58 | const relations = buildRelations(item.item.LearningUnit.learningUnitSource);
     | ^  59 | 
  60 | return (
  61 |   <DocumentTitle title={`Lerndorf | ${item.title}`}>

learningUnitsItemFetch/<
src/actions/learningUnits.js:86

  83 |     if (json.error) {
  84 |       // dispatch(userEditFailed(json.error, json.errors));
  85 |     } else {
> 86 |       dispatch(learningUnitsItemFetchSuccess(json));
     | ^  87 |     }
  88 |   }
  89 | } catch (e) {

**Comment by stylesuxx** [comment]
I am unable to reproduce this. We should talk about this.

**Comment by stylesuxx** [comment]
@cswertz Unfortunately I am still not able to reproduce it - see attached screenshot. Could you see if you can reproduce it on the latest dev branch? If so please post exact steps and output of `node --version`
![Screenshot from 2021-03-15 12-25-43](https://user-images.githubusercontent.com/978192/111146455-c100c900-8589-11eb-82d1-0d283524fccc.png)

**Comment by cswertz** [comment]
I did a fresh install (develop). Than I added a LU with language German. Than I tried to add an KU. Error (below).  When I recall the LU the KU is actually there and I can add content (editor works). When I try to add relations I can add a relation to the LU I'm starting with. That should not be possible. But: Setting relations does not lead to any result - no errors, no relations.

ERROR FOR KU IN CONSOLE
Could not open knowledgeUnits.js in the editor.

To set up the editor integration, add something like REACT_EDITOR=atom to the .env.local file in your project folder and restart the development server. Learn more: https://goo.gl/MMTaZt


ERROR IN BROWSER:
Unhandled Rejection (Error): Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
knowledgeUnitsItemFetch/<
src/actions/knowledgeUnits.js:62

  59 | 
  60 | export const knowledgeUnitsItemFetch = (id) => (
  61 |   async (dispatch) => {
> 62 |     await dispatch({
  63 |       type: types.KNOWLEDGEUNITS_ITEM_FETCH,
  64 |       id,
  65 |     });

fetchItem
src/containers/knowledgeUnits/Show.jsx:28

  25 |   } = match.params;
  26 | 
  27 |   if ((!items.fetching) && !items.id[id]) {
> 28 |     itemFetch(id);
     | ^  29 |   }
  30 | }
  31 | 

componentDidUpdate
src/containers/knowledgeUnits/Show.jsx:13

  10 | }
  11 | 
  12 | componentDidUpdate() {
> 13 |   this.fetchItem();
     | ^  14 | }
  15 | 
  16 | fetchItem() {

Router/_this.unlisten<
/home/cswertz/forschung/projects/1998_lerndorf/data/test/modules/Router.js:34

  31 | if (!props.staticContext) {
  32 |   this.unlisten = props.history.listen(location => {
  33 |     if (this._isMounted) {
> 34 |       this.setState({ location });
     | ^  35 |     } else {
  36 |       this._pendingLocation = location;
  37 |     }

knowledgeUnitsAdd/</<
src/actions/knowledgeUnits.js:107

  104 |       dispatch(knowledgeUnitsAddFailed(json.error, json.errors));
  105 |     } else {
  106 |       dispatch(knowledgeUnitsAddSuccess());
> 107 |       history.push(`/knowledge-units/show/${json.id}`);
      | ^  108 |     }
  109 |   }
  110 | })

**Comment by cswertz** [comment]
The error occurs if one of the LUs is new. The relations do work if the LUs from seeders are used. They do not work if the LUs are freshly created. I did a fresh install, created two LUs and tried to set relations among them. Result is as above. I can not set any relation. My guess (from variable name) is that the title for the LU (that is: the reference in LearningUnitLanguage) or the title for the relation (that is: the reference to TaxonomyLanguage) is not set. BTW: After the error occured, I can not even show the edit page for that LU. Bumps straight into TypeError: linkText[0] is undefined. Same problem if I set a relation from one "Se3eder LU" to a freshly created one. Now I can not edit any LUs in my installation any more :-(.

**Comment by stylesuxx** [comment]
I now tried every constellation of this, new with new, new with old, old with old, old with new - I simply can not reproduce this issue.
Also tried in Firefox just to make sure. The only way I could "reproduce" it was when I by accident opened the server in Firefox, which served an old build - might this be the case here?

I think we would need to have a screen share session in order to debug this properly.

**Comment by cswertz** [comment]
The error appears if I create a new LU with language "German" and try to set a link to a learning unit with language "English". Unfortunately the possibility to add a second language to a learning unit is still missing. Thus I can not add a second language to see it the error disappears.

**Comment by cswertz** [comment]
BTW: Setting links between LUs with same language works
