### ISSUE TITLE
Mysql errors

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#155]
Following error pops up with mysql:
-----------------------------------------------------------------------
sequelize db:migrate && sequelize db:seed:all && rm -rf ./build && webpack --config webpack.config.server.js

Sequelize CLI [Node: 12.16.2, CLI: 6.2.0, ORM: 6.3.4]

Loaded configuration file "server/config/babelHook.js".
Using environment "production_mysql".

ERROR: Please install mysql2 package manually

error Command failed with exit code 1.
----------------------------------------------------------------------
Interestingly, in the config file mysql (not mysql2) is required. In package.json, neither mysql nor mysql2 are required.

yarn add mysql2

helped - seems that dependencies are missing. Maybe add it?

Than the migration sequence did not work:
sequelize db:migrate && sequelize db:seed:all && rm -rf ./build && webpack --config webpack.config.server.js

Sequelize CLI [Node: 12.16.2, CLI: 6.2.0, ORM: 6.3.4]

Loaded configuration file "server/config/babelHook.js".
Using environment "production_mysql".
(node:243958) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
== 00010-Roles: migrating =======
== 00010-Roles: migrated (0.119s)

== 00015-Taxonomies: migrating =======
== 00015-Taxonomies: migrated (0.155s)

== 00020-Users: migrating =======

ERROR: Failed to open the referenced table 'UserLanguage'

mv 00070-UserLanguage.js 00001-UserLanguage.js

helped, but created:

ERROR: Failed to open the referenced table 'Users'

The tables are interdpenedent. Thus altering the sequence did not work.

I did not figure out how to stop mysql from checking the dependencies while creating the tables. Maybe we need to seperate table creation and dependency creation?

**Comment by stylesuxx** [comment]
Added mysql2 as a depenceny
