### ISSUE TITLE
Error when starting production

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#156]
When starting production instead of development with same parameters the following error pops up:

Sequelize CLI [Node: 12.16.2, CLI: 6.2.0, ORM: 6.3.4]

Loaded configuration file "server/config/babelHook.js".
Using environment "production".
(node:462770) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
== 00010-Roles: migrating =======

ERROR: Couldn't find preset "env" relative to directory "/var/www/ld/server/migrations"

**Comment by stylesuxx** [comment]
Which command are your running exactly and from which directory?
When running

    NODE_ENV=production SERVER_PORT=3030 yarn start

from the server dir, everything runs fine for me.

**Comment by cswertz** [comment]
Indeed - but with 
NODE_ENV=production_mysql
first
ERROR: Please install mysql2 package manually
pops up. After
yarn add mysql2
and 
yarn start I get:

sequelize db:migrate && sequelize db:seed:all && rm -rf ./build && webpack --config webpack.config.server.js

Sequelize CLI [Node: 12.16.2, CLI: 6.2.0, ORM: 6.3.4]

Loaded configuration file "server/config/babelHook.js".
Using environment "production_mysql".
(node:7106) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
== 00020-Users: migrating =======

ERROR: Failed to open the referenced table 'UserLanguage'

In mysql I get:

mysql> use ld_dev;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+------------------+
| Tables_in_ld_dev |
+------------------+
| Roles            |
| SequelizeMeta    |
| Taxonomies       |
+------------------+
3 rows in set (0.01 sec)
