### ISSUE TITLE
Model: Text

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#16]

**Comment by stylesuxx** [comment]
@cswertz I think it would be good to have a relation to the user who created the text - what do you think?

**Comment by cswertz** [comment]
Might a text belong to another user than the KU? I don't think so. If a new version of a text is created, the prior version needs to be kept in the database. Thus a copy has be be created and related to the new KU version - and prior authors need to be stored. And authors are stored in knowledgeunit_users. So the information should be there. And multiple authors can be stored there as well. Thus I would say: rather not.

**Comment by stylesuxx** [comment]
KU's have a relation to user, multiple users can thus be "owners" of a KU - at least that is how I understand the KnowledgeUnitUser relationship. If a KU can only be ownded by one user, I would suggest removing this relationship and instead make the relationship from the KU directly.

**Comment by cswertz** [comment]
@stylesuxx Yes - One KU can have multiple users. See the comment in the ERS: "Ownership of knowledgeunits. One KnowledgeUnit can be owned by one or many others. Authorship may change between version (version = kneolwdgeunits unique key = id_knowledgeunit/datetime)."

**Comment by cswertz** [comment]
@stylesuxx Datatype of ORM and ERS for content did not match. adjusted both to MEDIUMTEXT (64K seems a long text - if you are not from the humanities :-)
