### ISSUE TITLE
Setting languages for users: dupe entries when setting levels

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#169]
When setting a level for a language that already exists in the levels, a new entry in the database is set. That is: It is possible to set multiple entries for the same language with different or the same level. 
First: Set database unique key for UserId/LanguageId
Second: change backend to updating instead of inserting if language/user exists.

**Comment by cswertz** [comment]
Actually
unique: 'userIdLanguageId',
is set in migrations. Sqlite should consider it. But is doesn't. Maybe setting unique keys this way does  not to work?
According to this: https://github.com/sequelize/cli/issues/272 maybe a sequelize bug (or feature). As far as I see, there are two options: Write a migration file for indexes and unique keys or add indexes like this:

queryInterface.createTable('actions', {
            id: {
                type: Sequelize.INTEGER,
                primaryKey: true,
                autoIncrement: true
            },
            system_id: {
                type: Sequelize.STRING,
            },
            rule_id: {
                type: Sequelize.STRING,
            },
            plan_id: {
                type: Sequelize.INTEGER,
                unique: 'actions_unique',
            }
        }, {
            uniqueKeys: {
                actions_unique: {
                    fields: ['system_id', 'rule_id', 'plan_id']
                }
            }
        });

I'd prefer the second solution since you have the index in the migration in this case, which makes reading much easier. What do you think?

**Comment by stylesuxx** [comment]
Definetly the second option. I am under the impression that we use this variant in a different place already.

**Comment by cswertz** [comment]
OK, done.
