### ISSUE TITLE
Model: File

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#17]

**Comment by stylesuxx** [comment]
### Renamed:
* filename -> name

**Comment by cswertz** [comment]
@stylesuxx renamed table to Files in ERS, added createdAt to ERS. Removed updatedAt from ORM - Files can not be updated, but only deleted and replaced by a new one.

**Comment by cswertz** [comment]
added updatedAt again
changed "unique true" for path to unique: 'path' 'name' - there can be more than one file in a path.
