### ISSUE TITLE
Relation: UserRole

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#18]

**Comment by cswertz** [comment]
UserRole can't be updated. Roles can only be added and deleted. A change means deleting and adding an entry to this table. Thus I removed updatedAt and added CreatedAt to the ERS. createdAt changed to DATETIME.

**Comment by cswertz** [comment]
updatedAt and createdAt added again. 
added unique: 'userId' 'roleId',

**Comment by cswertz** [comment]
model was missing. created.

**Comment by cswertz** [comment]
@stylesuxx Roles changed to Singular, Users changed to Singular.
