### ISSUE TITLE
Endpoint for MyCourses

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#188]
Endpoint for my courses, data should include all courses I visit and all courses I created; my role in the course (student, teacher), and the last position in the course (to create a link that allows to continue a course where I left, unless that is easier achieved when actually calling a course).

**Comment by stylesuxx** [comment]
@cswertz I am a bit confused here - we do not have course functionality yet - only the migrations and models. Could you please create some seeders, then I will create the according endpoints.

**Comment by cswertz** [comment]
OK. Tomorrow Morning.

**Comment by leganz** [comment]
GET Endpoints will be provided within the PR for #186

**Comment by leganz** [comment]
Should be resolved with #212

**Comment by cswertz** [comment]
It is.
