### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#2]
@cswertz In order to be able to push to this repository, create labels and milestones my user needs to be added to this repository as an admin.

Alternatively I can submit PR's and you merge them into the main repo and I ask in issues for labels and milestones to be added. Whichever you prefer.

* [x]  Add @stylesuxx as admin
* [x]  Setup milestones
* [x]  Setup labels
* [x]  Initialize [gitflow](https://datasift.github.io/gitflow/IntroducingGitFlow.html)
* [x]  Add @gabseifon to this repo

**Comment by cswertz** [comment]
I hope I hit the right button.

**Comment by stylesuxx** [comment]
Yes, seems good - thank you.

**Comment by stylesuxx** [comment]
We should not forget to add Gabriel to this repo - not sure if he has a github account yet. Should I ping him, or will you @cswertz ?

**Comment by cswertz** [comment]
Might make sense if you do it. Thx!

**Comment by gabseifon** [comment]
I'm here

**Comment by gabseifon** [comment]
Hallo

**Comment by cswertz** [comment]
Looks good.
