### ISSUE TITLE
Relation: LearningunitLanguage

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#22]

**Comment by stylesuxx** [comment]
### Renamed
* id_user -> UserId
* id_language -> LanguageId

**Comment by cswertz** [comment]
@stylesuxx updatedAT and createdAT changed to DATETIME and added to ERS.  Changed title from STRING to MEDIUMTEXT. Added compisite PrimaryKey.

**Comment by cswertz** [comment]
changed Type to TEXT('medium')
changed queryInterface.dropTable('TaxonomyLanguage') to queryInterface.dropTable('LearningUnitLanguage')
added   unique: 'learningUnitId languageId',
added updatedAt to ERS

**Comment by cswertz** [comment]
unique: 'learningUnitsRootIdCreatedAt' seems not correct. Changed to unique: 'id createdAt',
