### ISSUE TITLE
Workflow when adding new courses 

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#233]
After adding a new course an empty page is shown. Expected: The List "My Courses" with the new course in the list.

**Comment by leganz** [comment]
@cswertz does it mean you do not have that ux? https://share.cleanshot.com/9mbBt5WZC3zfNtJlPjZg

**Comment by leganz** [comment]
Please review: https://github.com/cswertz/lerndorf/pull/247

**Comment by cswertz** [comment]
moved to #247
