### ISSUE TITLE
editing of courses does not work

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#234]
The edit function for new courses can not be invoked. Probably connected to #233

**Comment by leganz** [comment]
@cswertz can you please provide more information. I have tested the update/edit process and it works as expected (https://share.cleanshot.com/WYMZq17zkrmxL9zNV33q)

**Comment by cswertz** [comment]
@leganz  With fresh database: unfortunately not: [https://192.168.178.2/index.php/s/QYtiAnRzwnYWkXM](url)

**Comment by cswertz** [comment]
Sorry - external link is needed here: https://swertz.org/index.php/s/QYtiAnRzwnYWkXM

**Comment by cswertz** [comment]
I tried to delete one of the courses (the titeles show up in the list after reload but can not be edited). Fortunately, this caused an error: 
![grafik](https://user-images.githubusercontent.com/15083008/216330309-02c0658b-285e-43cc-a9f0-a0d0c68033f7.png)

**Comment by cswertz** [comment]
Confirmation message is still shown and course is actually deleted (at least from the list).

**Comment by leganz** [comment]
The problem with deletion is a binding issue. But it is rly weirrd that you can't see the second part of the creation dialog. 
Are threre any console log issues? Could you do me the favor and run npm i after you removed the node_modules folder

**Comment by cswertz** [comment]
cswertz@cswertz-desktop-arbeitszimmer:~/forschung/projects/1998_lerndorf/data/lerndorf$ npm i
up to date in 0.332s
found 0 vulnerabilities

cswertz@cswertz-desktop-arbeitszimmer:~/forschung/projects/1998_lerndorf/data/lerndorf$  node -v
v12.16.2

**Comment by cswertz** [comment]
Fehler vom Browserlog:
FrameData missing for uBlock0@raymondhill.net page moz-extension://fce3c181-d1da-4040-b8ec-9762518b4372/popup-fenix.html [ExtensionPageChild.jsm:466](resource://gre/modules/ExtensionPageChild.jsm)
    initExtensionContext resource://gre/modules/ExtensionPageChild.jsm:466
    initExtensionDocument resource://gre/modules/ExtensionProcessScript.jsm:376
----------------------
Warning: Failed prop type: The prop `course.item` is marked as required in `Router`, but its value is `null`.
Router@http://localhost:3001/static/js/main.chunk.js:253:16
ConnectFunction@http://localhost:3001/static/js/vendors~main.chunk.js:405456:75
Router@http://localhost:3001/static/js/vendors~main.chunk.js:407933:30
BrowserRouter@http://localhost:3001/static/js/vendors~main.chunk.js:407553:35
ThemeProvider@http://localhost:3001/static/js/vendors~main.chunk.js:275226:18
PersistGate@http://localhost:3001/static/js/vendors~main.chunk.js:427392:20
Provider@http://localhost:3001/static/js/vendors~main.chunk.js:405169:15
App [vendors~main.chunk.js:403903:20](http://localhost:3001/static/js/vendors~main.chunk.js)
    e http://localhost:3001/static/js/vendors~main.chunk.js:403903
    printWarning http://localhost:3001/static/js/vendors~main.chunk.js:417174
    error http://localhost:3001/static/js/vendors~main.chunk.js:417150
    checkPropTypes http://localhost:3001/static/js/vendors~main.chunk.js:418854
    validatePropTypes http://localhost:3001/static/js/vendors~main.chunk.js:419051
    createElementWithValidation http://localhost:3001/static/js/vendors~main.chunk.js:419152
    renderedWrappedComponent http://localhost:3001/static/js/vendors~main.chunk.js:405568
    mountMemo http://localhost:3001/static/js/vendors~main.chunk.js:392190
    useMemo http://localhost:3001/static/js/vendors~main.chunk.js:392557
    useMemo http://localhost:3001/static/js/vendors~main.chunk.js:418456
    ConnectFunction http://localhost:3001/static/js/vendors~main.chunk.js:405567
    renderWithHooks http://localhost:3001/static/js/vendors~main.chunk.js:391352
    updateFunctionComponent http://localhost:3001/static/js/vendors~main.chunk.js:393674
    updateSimpleMemoComponent http://localhost:3001/static/js/vendors~main.chunk.js:393539
    updateMemoComponent http://localhost:3001/static/js/vendors~main.chunk.js:393418
    beginWork http://localhost:3001/static/js/vendors~main.chunk.js:395398
    beginWork$1 http://localhost:3001/static/js/vendors~main.chunk.js:400129
    performUnitOfWork http://localhost:3001/static/js/vendors~main.chunk.js:398989
    workLoopSync http://localhost:3001/static/js/vendors~main.chunk.js:398926
    renderRootSync http://localhost:3001/static/js/vendors~main.chunk.js:398892
    performSyncWorkOnRoot http://localhost:3001/static/js/vendors~main.chunk.js:398509
    flushSyncCallbackQueueImpl http://localhost:3001/static/js/vendors~main.chunk.js:387762
    unstable_runWithPriority http://localhost:3001/static/js/vendors~main.chunk.js:430559
    runWithPriority$1 http://localhost:3001/static/js/vendors~main.chunk.js:387708
    flushSyncCallbackQueueImpl http://localhost:3001/static/js/vendors~main.chunk.js:387757
    flushSyncCallbackQueue http://localhost:3001/static/js/vendors~main.chunk.js:387745
    scheduleUpdateOnFiber http://localhost:3001/static/js/vendors~main.chunk.js:398109
    enqueueSetState http://localhost:3001/static/js/vendors~main.chunk.js:388885
    setState http://localhost:3001/static/js/vendors~main.chunk.js:417315
    PersistGate http://localhost:3001/static/js/vendors~main.chunk.js:427420
    dispatch http://localhost:3001/static/js/vendors~main.chunk.js:428592
    rehydrate http://localhost:3001/static/js/vendors~main.chunk.js:427885
    _rehydrate http://localhost:3001/static/js/vendors~main.chunk.js:427642
    persistReducer http://localhost:3001/static/js/vendors~main.chunk.js:427671
-----------------------------------------------------------
Warning: Failed prop type: Invalid prop `courselists.items` of type `array` supplied to `Router`, expected `object`.
Router@http://localhost:3001/static/js/main.chunk.js:253:16
ConnectFunction@http://localhost:3001/static/js/vendors~main.chunk.js:405456:75
Router@http://localhost:3001/static/js/vendors~main.chunk.js:407933:30
BrowserRouter@http://localhost:3001/static/js/vendors~main.chunk.js:407553:35
ThemeProvider@http://localhost:3001/static/js/vendors~main.chunk.js:275226:18
PersistGate@http://localhost:3001/static/js/vendors~main.chunk.js:427392:20
Provider@http://localhost:3001/static/js/vendors~main.chunk.js:405169:15
App [vendors~main.chunk.js:403903:20](http://localhost:3001/static/js/vendors~main.chunk.js)
    e http://localhost:3001/static/js/vendors~main.chunk.js:403903
    printWarning http://localhost:3001/static/js/vendors~main.chunk.js:417174
    error http://localhost:3001/static/js/vendors~main.chunk.js:417150
    checkPropTypes http://localhost:3001/static/js/vendors~main.chunk.js:418854
    validatePropTypes http://localhost:3001/static/js/vendors~main.chunk.js:419051
    createElementWithValidation http://localhost:3001/static/js/vendors~main.chunk.js:419152
    renderedWrappedComponent http://localhost:3001/static/js/vendors~main.chunk.js:405568
    mountMemo http://localhost:3001/static/js/vendors~main.chunk.js:392190
    useMemo http://localhost:3001/static/js/vendors~main.chunk.js:392557
    useMemo http://localhost:3001/static/js/vendors~main.chunk.js:418456
    ConnectFunction http://localhost:3001/static/js/vendors~main.chunk.js:405567
    renderWithHooks http://localhost:3001/static/js/vendors~main.chunk.js:391352
    updateFunctionComponent http://localhost:3001/static/js/vendors~main.chunk.js:393674
    updateSimpleMemoComponent http://localhost:3001/static/js/vendors~main.chunk.js:393539
    updateMemoComponent http://localhost:3001/static/js/vendors~main.chunk.js:393418
    beginWork http://localhost:3001/static/js/vendors~main.chunk.js:395398
    beginWork$1 http://localhost:3001/static/js/vendors~main.chunk.js:400129
    performUnitOfWork http://localhost:3001/static/js/vendors~main.chunk.js:398989
    workLoopSync http://localhost:3001/static/js/vendors~main.chunk.js:398926
    renderRootSync http://localhost:3001/static/js/vendors~main.chunk.js:398892
    performSyncWorkOnRoot http://localhost:3001/static/js/vendors~main.chunk.js:398509
    flushSyncCallbackQueueImpl http://localhost:3001/static/js/vendors~main.chunk.js:387762
    unstable_runWithPriority http://localhost:3001/static/js/vendors~main.chunk.js:430559
    runWithPriority$1 http://localhost:3001/static/js/vendors~main.chunk.js:387708
    flushSyncCallbackQueueImpl http://localhost:3001/static/js/vendors~main.chunk.js:387757
    flushSyncCallbackQueue http://localhost:3001/static/js/vendors~main.chunk.js:387745
    scheduleUpdateOnFiber http://localhost:3001/static/js/vendors~main.chunk.js:398109
    enqueueSetState http://localhost:3001/static/js/vendors~main.chunk.js:388885
    setState http://localhost:3001/static/js/vendors~main.chunk.js:417315
    PersistGate http://localhost:3001/static/js/vendors~main.chunk.js:427420
    dispatch http://localhost:3001/static/js/vendors~main.chunk.js:428592
    rehydrate http://localhost:3001/static/js/vendors~main.chunk.js:427885
    _rehydrate http://localhost:3001/static/js/vendors~main.chunk.js:427642
    persistReducer http://localhost:3001/static/js/vendors~main.chunk.js:427671
-----------------------------------------------------------
Warning: Failed prop type: The prop `courselist.item` is marked as required in `Router`, but its value is `null`.
Router@http://localhost:3001/static/js/main.chunk.js:253:16
ConnectFunction@http://localhost:3001/static/js/vendors~main.chunk.js:405456:75
Router@http://localhost:3001/static/js/vendors~main.chunk.js:407933:30
BrowserRouter@http://localhost:3001/static/js/vendors~main.chunk.js:407553:35
ThemeProvider@http://localhost:3001/static/js/vendors~main.chunk.js:275226:18
PersistGate@http://localhost:3001/static/js/vendors~main.chunk.js:427392:20
Provider@http://localhost:3001/static/js/vendors~main.chunk.js:405169:15
App [vendors~main.chunk.js:403903:20](http://localhost:3001/static/js/vendors~main.chunk.js)
    e http://localhost:3001/static/js/vendors~main.chunk.js:403903
    printWarning http://localhost:3001/static/js/vendors~main.chunk.js:417174
    error http://localhost:3001/static/js/vendors~main.chunk.js:417150
    checkPropTypes http://localhost:3001/static/js/vendors~main.chunk.js:418854
    validatePropTypes http://localhost:3001/static/js/vendors~main.chunk.js:419051
    createElementWithValidation http://localhost:3001/static/js/vendors~main.chunk.js:419152
    renderedWrappedComponent http://localhost:3001/static/js/vendors~main.chunk.js:405568
    mountMemo http://localhost:3001/static/js/vendors~main.chunk.js:392190
    useMemo http://localhost:3001/static/js/vendors~main.chunk.js:392557
    useMemo http://localhost:3001/static/js/vendors~main.chunk.js:418456
    ConnectFunction http://localhost:3001/static/js/vendors~main.chunk.js:405567
    renderWithHooks http://localhost:3001/static/js/vendors~main.chunk.js:391352
    updateFunctionComponent http://localhost:3001/static/js/vendors~main.chunk.js:393674
    updateSimpleMemoComponent http://localhost:3001/static/js/vendors~main.chunk.js:393539
    updateMemoComponent http://localhost:3001/static/js/vendors~main.chunk.js:393418
    beginWork http://localhost:3001/static/js/vendors~main.chunk.js:395398
    beginWork$1 http://localhost:3001/static/js/vendors~main.chunk.js:400129
    performUnitOfWork http://localhost:3001/static/js/vendors~main.chunk.js:398989
    workLoopSync http://localhost:3001/static/js/vendors~main.chunk.js:398926
    renderRootSync http://localhost:3001/static/js/vendors~main.chunk.js:398892
    performSyncWorkOnRoot http://localhost:3001/static/js/vendors~main.chunk.js:398509
    flushSyncCallbackQueueImpl http://localhost:3001/static/js/vendors~main.chunk.js:387762
    unstable_runWithPriority http://localhost:3001/static/js/vendors~main.chunk.js:430559
    runWithPriority$1 http://localhost:3001/static/js/vendors~main.chunk.js:387708
    flushSyncCallbackQueueImpl http://localhost:3001/static/js/vendors~main.chunk.js:387757
    flushSyncCallbackQueue http://localhost:3001/static/js/vendors~main.chunk.js:387745
    scheduleUpdateOnFiber http://localhost:3001/static/js/vendors~main.chunk.js:398109
    enqueueSetState http://localhost:3001/static/js/vendors~main.chunk.js:388885
    setState http://localhost:3001/static/js/vendors~main.chunk.js:417315
    PersistGate http://localhost:3001/static/js/vendors~main.chunk.js:427420
    dispatch http://localhost:3001/static/js/vendors~main.chunk.js:428592
    rehydrate http://localhost:3001/static/js/vendors~main.chunk.js:427885
    _rehydrate http://localhost:3001/static/js/vendors~main.chunk.js:427642
    persistReducer http://localhost:3001/static/js/vendors~main.chunk.js:427671
----------------------------------
Warning: Failed prop type: The prop `errors` is marked as required in `Create`, but its value is `undefined`.
Create@http://localhost:3001/static/js/main.chunk.js:12975:16
Form@http://localhost:3001/static/js/vendors~main.chunk.js:422986:41
ConnectFunction@http://localhost:3001/static/js/vendors~main.chunk.js:405456:75
Connect(Form(Create))
ReduxForm@http://localhost:3001/static/js/vendors~main.chunk.js:423726:43
Hoc@http://localhost:3001/static/js/vendors~main.chunk.js:420415:31
ReduxForm
WithStyles@http://localhost:3001/static/js/vendors~main.chunk.js:276524:25
CreateCourse@http://localhost:3001/static/js/main.chunk.js:31922:1
C@http://localhost:3001/static/js/vendors~main.chunk.js:408555:31
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
CoursesRouter@http://localhost:3001/static/js/main.chunk.js:37496:23
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
PrivateRoute@http://localhost:3001/static/js/main.chunk.js:6029:22
Switch@http://localhost:3001/static/js/vendors~main.chunk.js:408500:29
div
main
div
Wrapper@http://localhost:3001/static/js/main.chunk.js:8084:17
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
Switch@http://localhost:3001/static/js/vendors~main.chunk.js:408500:29
Router@http://localhost:3001/static/js/main.chunk.js:253:16
ConnectFunction@http://localhost:3001/static/js/vendors~main.chunk.js:405456:75
Router@http://localhost:3001/static/js/vendors~main.chunk.js:407933:30
BrowserRouter@http://localhost:3001/static/js/vendors~main.chunk.js:407553:35
ThemeProvider@http://localhost:3001/static/js/vendors~main.chunk.js:275226:18
PersistGate@http://localhost:3001/static/js/vendors~main.chunk.js:427392:20
Provider@http://localhost:3001/static/js/vendors~main.chunk.js:405169:15
App
-----------------------------------------------
Warning: Failed prop type: The prop `spacing` of `Grid` must be used on `container`.
WithStyles@http://localhost:3001/static/js/vendors~main.chunk.js:276524:25
ListView@http://localhost:3001/static/js/main.chunk.js:15540:18
WithStyles@http://localhost:3001/static/js/vendors~main.chunk.js:276524:25
MyCourses@http://localhost:3001/static/js/main.chunk.js:32839:1
C@http://localhost:3001/static/js/vendors~main.chunk.js:408555:31
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
CoursesRouter@http://localhost:3001/static/js/main.chunk.js:37496:23
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
PrivateRoute@http://localhost:3001/static/js/main.chunk.js:6029:22
Switch@http://localhost:3001/static/js/vendors~main.chunk.js:408500:29
div
main
div
Wrapper@http://localhost:3001/static/js/main.chunk.js:8084:17
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
Switch@http://localhost:3001/static/js/vendors~main.chunk.js:408500:29
Router@http://localhost:3001/static/js/main.chunk.js:253:16
ConnectFunction@http://localhost:3001/static/js/vendors~main.chunk.js:405456:75
Router@http://localhost:3001/static/js/vendors~main.chunk.js:407933:30
BrowserRouter@http://localhost:3001/static/js/vendors~main.chunk.js:407553:35
ThemeProvider@http://localhost:3001/static/js/vendors~main.chunk.js:275226:18
PersistGate@http://localhost:3001/static/js/vendors~main.chunk.js:427392:20
Provider@http://localhost:3001/static/js/vendors~main.chunk.js:405169:15
App
---------------------------------------
Warning: Failed prop type: The prop `course` is marked as required in `ListView`, but its value is `undefined`.
ListView@http://localhost:3001/static/js/main.chunk.js:15540:18
WithStyles@http://localhost:3001/static/js/vendors~main.chunk.js:276524:25
MyCourses@http://localhost:3001/static/js/main.chunk.js:32839:1
C@http://localhost:3001/static/js/vendors~main.chunk.js:408555:31
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
CoursesRouter@http://localhost:3001/static/js/main.chunk.js:37496:23
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
PrivateRoute@http://localhost:3001/static/js/main.chunk.js:6029:22
Switch@http://localhost:3001/static/js/vendors~main.chunk.js:408500:29
div
main
div
Wrapper@http://localhost:3001/static/js/main.chunk.js:8084:17
Route@http://localhost:3001/static/js/vendors~main.chunk.js:408298:29
Switch@http://localhost:3001/static/js/vendors~main.chunk.js:408500:29
Router@http://localhost:3001/static/js/main.chunk.js:253:16
ConnectFunction@http://localhost:3001/static/js/vendors~main.chunk.js:405456:75
Router@http://localhost:3001/static/js/vendors~main.chunk.js:407933:30
BrowserRouter@http://localhost:3001/static/js/vendors~main.chunk.js:407553:35
ThemeProvider@http://localhost:3001/static/js/vendors~main.chunk.js:275226:18
PersistGate@http://localhost:3001/static/js/vendors~main.chunk.js:427392:20
Provider@http://localhost:3001/static/js/vendors~main.chunk.js:405169:15
App [vendors~main.chunk.js:403903:20](http://localhost:3001/static/js/vendors~main.chunk.js)
---------------------------------------------

**Comment by leganz** [comment]
There has been a modification which address the problems described here in the PR https://github.com/cswertz/lerndorf/pull/247

**Comment by cswertz** [comment]
moved to PR #247
