### ISSUE TITLE
Menu not shown after "My Courses" is called.

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#235]
After "My Courses" is clicked in Dashboard the left Menu is empty. It's probably a good idea to show the Dashboard - Menu until a course is activated since the list of the courses is shown in the main window anyway.

**Comment by leganz** [comment]
I rather would suggest to show always the menu to be communicate a clear "path". I think it would be more confusing if the navigation change if the state of one course changes.

https://github.com/cswertz/lerndorf/pull/249

**Comment by cswertz** [comment]
If you enter a course, you would probably like to navigate the content. That's why the menu should show the titles of the learning units in the course after a course is started. Whatever: The Menu is there after "My Courses" is cklicked. So: fixed. THX!
