### ISSUE TITLE
No new threads possible

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#237]
It is not possible to add new threads in a forum - no "+" - Button below the list of threads.

**Comment by leganz** [comment]
PR #240  should fix that

**Comment by leganz** [comment]
Regarding the "below" - should we rly add the button only under the list? The list might become very long

**Comment by leganz** [comment]
I have created a PR https://github.com/cswertz/lerndorf/pull/245 to resolve this issue.

**Comment by cswertz** [comment]
@leganz Works. I forgot to specify file uploads. My fault. Not important now. Courses first ...
