### ISSUE TITLE
Manage Taxonomies - change symbols

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#238]
in "manage taxonomies" active entries have an "x" as entry. this changes to a checkmark after deactivating the entry. that's not intuitive - it would be better to exchange the symbols. that is: all active entries are marked with a checkmark and the not active ones with an "x".

**Comment by leganz** [comment]
as described this might be weirrd 
=> current behavior https://share.cleanshot.com/ksSPDXCsqJt6nrFb4Tx8

Has been change in https://github.com/cswertz/lerndorf/pull/248

**Comment by cswertz** [comment]
We''ll see what the audience says. Looks better now IMHO. Thx!
