### ISSUE TITLE
Menu with Learning Units, Knowledge Units and Media Units is not shown

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#239]
Either the endpoints (#196, #187, #186) are not working or not connected to the UI. In any case: After calling http://localhost:3001/learning-units/ a list of available learning units should be shown in the left menu. Instead, a list of courses is shown.

**Comment by leganz** [comment]
I will check that. Might be related to the "courselist" feature.

**Comment by leganz** [comment]
https://github.com/cswertz/lerndorf/pull/250

Issue was caused by invalid call

**Comment by cswertz** [comment]
Works fine.
