### ISSUE TITLE
Deploy Dev Env

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#3]
Deploy the dev env on the dev server.

* [x]  @cswertz please make one port accessible from the outside, maybe port 8000 or 3000, they seem to be firewalled
* [x]  Install NVM & latest nodeJS stable version
* [x]  Clone and setup repository
* [x] Install apache, set proxy pass from port 80 to 8000

**Comment by cswertz** [comment]
Ports are open (at least on server). nvm and node 8.9.4. installed.

**Comment by stylesuxx** [comment]
I installed node already via nvm. No prefered location, I can clone it myself, in the root of the user is OK for me.

Still I can not reach the server from the outside on a different port than for ssh...

I am testing with this python one liner to make sure if I can access or not:

    python3 -m http.server

this spawns a server on port 8000 and serves the current directory, right now I am not able to connect from the outside.

**Comment by stylesuxx** [comment]
Sure, but those ports are so low, that I would need sudo to run anything on them - my user does not seem to have sudo though ;-)

**Comment by cswertz** [comment]
Central Service says the port is open now. Rights added to user. Solved?

**Comment by cswertz** [comment]
And yes - the user is OK for cloning in the root.

**Comment by stylesuxx** [comment]
Can still not access it from the outside at port 8000... Port 80 is working with sudo.
Firewall does not seem to be the problem though. Would really love not having to run the code with sudo. Maybe I install apache and proxyPass port 80 to 8000, this way I can run apache as root and be able to run the code as normal user at port 8000 and the redirect is simply happening locally.

**Comment by cswertz** [comment]
Yes, an apache redirect is probably the quickest solution and gives us some flexibility later on.

**Comment by stylesuxx** [comment]
Setup apache, redirect port 80 to port 8000. Closed.
