### ISSUE TITLE
MySql Workbench Model broken

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#32]
I just pulled in the changes, it seems the model is broken, I miss the User entity...
I pushed my variant instead - maybe you could make your changes on that again please.

**Comment by cswertz** [comment]
@stylesuxx OK - done. I would like to suggest to add the privacylevels to the taxonomy. I changed the comment in the user tables accordingly and added a foreign key. Since all IDs are integers in the migrations already, not further changes were necessary.

**Comment by stylesuxx** [comment]
Adjusted relation.
