### ISSUE TITLE
Renaming of Models

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#37]
I have seen that the models have been wildly renamed...
I am not all to happy about that - my thinking of the naming convention is like so: A Model describes an entity, thus it is in the context of *singular*.

Now some models are in plural, like *Users* and some in singular like *LogUser* to me this makes little sense. if you are against singular in model names, we can have it plural, but then we should be consistent about it, and have it everywhere.

I am not entirely sure why such a big change has been made without discussion. 

This has massive implications on everywhere the Model is used...

**Comment by cswertz** [comment]
Reversed.
