### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#38]
Since a lot of stuff has been changed, the tests are failing => https://travis-ci.org/cswertz/lerndorf

Please fix this accordingly. I am not sure if it makes sense to discuss all the changes via Issues right now. I would like to meet and discuss this in person also with @gabseifon I think this is more productive than discussing all the issues separately.

**Comment by cswertz** [comment]
@stylesuxx Yes - a meeting is a good idea. I tried to make naming more consistent - but obviously intrepreted some things wrong. I can of course revert everything to the suggested conventions (it seems I didn't analyse them correctly). Next week Monday between 10-12 or after 17:30 or Wednesday after 16:30 would be good if we can meet in the University. Would that be OK for you?

**Comment by stylesuxx** [comment]
Monday after 17:30 would be OK for me. This way we lose the least time I think. We can meet at University, just tell me where to come to. Feel free to mail me the location: stylesuxx@gmail.com

**Comment by cswertz** [comment]
THX!
