### ISSUE TITLE
Base Setup and configuration (Backend)

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#4]
This is the main ticket for the *Base Setup and configuration* Milestone:
* [x]  Folder structure for client/server/doc
* [x]  General Readme
* [x]  Server Readme
* [x]  Travis CI integration (Backend) => #5
* [x]  Badges: Dependencies (Backend)
* [x]  Dependency management via yarn
* [x]  Passport base setup, locally register user, locally authenticate user
* [x]  Sequelize base setup, sqlite db for dev (this can be changed later to any other database supported by sequelize eg.: mysql)
* [x]  Script for linting
* [x]  Script for testing
* [x]  Script for test watcher
* [x]  Code Coverage
* [x]  Configuration of migrations via sequelize CLI
* [x]  Configuration of seeders via sequelize CLI

Feel free to open issues for any of those tasks if more information is required, make sure to link here from the new issue and check the appropriate item here, so that we do not have duplicates.

**Comment by stylesuxx** [comment]
@cswertz @gabseifon 
The features for the first Milestone are ready for approval. as soon as it is approved I will make a new Release, as described in #6 and we can move on with the next milestone.

**Comment by cswertz** [comment]
@stylesuxx 
Looks good and simple - and simple is the best :-)
Just one question: Database tables for users and roles do not follow the specs yet. Well - that's a later milestone, but wouldn't it be easier to set them up as planned right away?

**Comment by stylesuxx** [comment]
Does not really matter, this is the minimum configuration needed. Everything else can be added via migrations later on. Since I am using sqlite (at least for development) I can easily delete the DB, spawn a new one and run the migrations to get the tables configured - the seeders will then fill the tables with dummy data. The idea was to just have the bare minimum to configure registration and login via passport.

I have a bit time left on this milestone, so technically I could start adding the fields now if you prefer.

**Comment by cswertz** [comment]
@gabseifon @stylesuxx 
Perfect. I hereby approve the first milestone. Look forward for the next one!

**Comment by cswertz** [comment]
@stylesuxx 
Dependencies should be updated occasionally. I got:
"We found potential security vulnerabilities in your dependencies."

**Comment by stylesuxx** [comment]
Closing this - dependency updates have their own ticket here #75
