### ISSUE TITLE
Approval: Roles and Permissions

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#44]

**Comment by stylesuxx** [comment]
Deployed to dev, ready for review

**Comment by cswertz** [comment]
Looks good. All Roles are there. Basic permission is there.

**Comment by cswertz** [comment]
@stylesuxx One hint: In RolesLanguages the entries for the roles are not made. Should I add the necessary entries as seeders?

**Comment by stylesuxx** [comment]
Would be great, thank you.

**Comment by cswertz** [comment]
@stylesuxx Entries are there. Can not see if they are used since language can not be set. Consider it as done here.
