### ISSUE TITLE
Seeder: Create Capabilities

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#46]
Permissions are a central Element of Role Management, they are added "hard coded" since they are queried through various places of the app. Adding them dynamically would make no sense. Further permissions might be added when the need for them arises.

**Comment by stylesuxx** [comment]
@cswertz I added some notes to the capabilites sheet in the google doc. Can you please check the ones marked with orange - if what I write is OK for you, please mark them green, otherwise please add your input, either here or there. If there, please highlight in a different color.

**Comment by cswertz** [comment]
@stylesuxx Looks pretty good - thank's. Everything green - some minor remarks in purple. And - sorry for the delay....

**Comment by cswertz** [comment]
@stylesuxx: Some suggestions from reviewing 00040-Capabilities.js
- Change slug "set_knowledge_unit_review" to "set_knowledge_unit_reviewed" (like "set_knowledge_unit_lectored")? Name for review is already in past tense.
- Is a slug for "edit_own_user" necessary (exists in drive - document, but not in 00040-Capabilities.js)?
- Probably a slug for "delete_own_user" is necessary?
- Add a slug "add_language_to_user" and "delete_language_from_user" to allow admins to do this?
- Is a slug for "delete_file" (in contrast to the existing "delete_any_file" missing?

**Comment by stylesuxx** [comment]
1. Renamed
2. No - IMHO this is implicit - a user can always edit himself
3. Yes - added
4. As discussed - this is implicit by the "edit user" capability
5. Implicit - User can edit (and thus also delete) their own content

**Comment by cswertz** [comment]
@stylesuxx There is "add_role_to_user" and "add_role". Does "add_role_to_user" mean "add role to own account"? If not - what's the difference?

**Comment by cswertz** [comment]
@stylesuxx It seems that "delete_file" is missing as a capability. Same for "edit_capability_of_role".

**Comment by stylesuxx** [comment]
Check "delete_file" - why is it not present yet?

**Comment by stylesuxx** [comment]
delete_file is not present since file deletion does not make sense - the file is part of the content. You can add a new version of the content and omit the file there, but it still needs to be part of the old content.

@cswertz maybe I am missing something here. In which case would it make sense to delete a file in your opinioin. delete_any_file is present for admin users to delete a file if it violates TOS.

**Comment by cswertz** [comment]
@stylesuxx OK. So creating content or a new version of content includes the capability to delete one file (a picture for example) from that content. Mkes sense for me. Thank's for crosschecking.
