### ISSUE TITLE
Logic: Check for Role

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#49]

**Comment by cswertz** [comment]
Bug: Roles are not shown when "edit" is called; they are shown in "edit" after "view" is called
Reproduction:
Fresh Install
call "Administration -> Manage Roles"
click edit

**Comment by stylesuxx** [comment]
Capabilities are not show on inital edit load of the role.

**Comment by cswertz** [comment]
Capabilities are shown and can be changed. Defaults look good. One exemption: For role lector the capability "Mark a Knowledge Uni as reviewed" should be set. I added that (and lectored too).

**Comment by cswertz** [comment]
As far as I see languages are not supported yet: I can not edit translations (RoleLanguage). It is possible to edit the default, but that's probably not the vocable from RolesLanguages, is it?
