### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#5]
* [x]  Add to travis CI
* [x]  Configure travis CI
* [x]  Enable Badges

@cswertz can you please add this repo to [Travis CI](https://travis-ci.org)? I will do the rest of the needed configuration, but can not add it myself, since I am not owner of the repo.

**Comment by cswertz** [comment]
Hope again that I've hit the right button - repo was shown at travis, so looks good IMHO

**Comment by stylesuxx** [comment]
Yes, looking good - thank you.
