### ISSUE TITLE
Seeder: Attach Capabilities to Roles

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#52]

**Comment by stylesuxx** [comment]
@cswertz as mentioned in #46 please review the google sheet.

**Comment by cswertz** [comment]
Done. Looks good. How will translations for Roles be inserted? Via seeders?

**Comment by stylesuxx** [comment]
Yes, as discussed - Translations will be added via seeders.

**Comment by cswertz** [comment]
Looks good.
