### ISSUE TITLE
Migrations: id Languages as autoincrement is problematic

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#54]
@stylesuxx Setting id to autoincrement in lanugages seems problematic since ther are n:m relations that refer to this ID. It seem thus difficult to create seeders for  TaxonomyLanguage since I can't be sure about the LanguageID. Is that right? If so, I would like to suggest to remove "autoincrement" from languages and add ids in languages manually.

**Comment by stylesuxx** [comment]
ID's can be set manually in the seeders - so technically this should not be a problem. Also you can run queries in the seeders and for example get the ID by the languages "code"

**Comment by cswertz** [comment]
OK. Makes sense. I set autoincrecmet: false for the ID of languages.
