### ISSUE TITLE
Taxonomies

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#64]
* Taxonomies can not be deleted, even if I create a new one that's not
used anywhere. To delete used ones should not be possible, so that's fine.
* editing of taxonomies does not work
* viewing taxonomies does not work.

**Comment by stylesuxx** [comment]
@cswertz I can not reproduce this one - viewing, editing and deleting works without any problems on my side. I can just imagine that this was a problem of remote access. Maybe it would be a good idea to deploy and test locally.

**Comment by cswertz** [comment]
@stylesuxx 
In a local installation:
- deleting works OK
- editing works OK
- viewing works OK
Thus considered as OK. Thx!
