### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#68]
* Users can not be edited (makes sense for profile to improve data
protection, but setting access rights is needed)

* Users can not be deleted or deactivated

**Comment by stylesuxx** [comment]
As with #64 and #66 editing is working for me.

User deletion was not specced. I can add a button to "mark a user" as deleted - what implications would that have on content he owns / partially owns - should it no longer be displayed?

**Comment by cswertz** [comment]
Complicated indeed. To make is simple:
- If the user did not create  content: or courses: remove his posts from forums, remove log entries, delete account (tell the user  what will be deleted before and confirm that it has been deleted after)
- if the user created courses: Tell him he should delete the courses first and show a list of courses he owns.. 
- if he user created content: Tell him  that he has to delete the content first and show a list of his content items. 

I guess I need to think about content deletion too - but that's another issue.

**Comment by stylesuxx** [comment]
User can be anonymized, and locked, by removing details that identify him.
He will then no longer be able to login, his username will be changed to [DELETED $ID]

If the user has no content attached to him, he can be deleted without any issues
