### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#69]
## Additional Fields
* [x] state should be offered (for people from US)
* [x] A dropdown list for country might make sense (if not to much hassle)
* [x] Checkbox Privacy Policy
* [x] Checkbox Terms and Conditions
* [x] Link to Privacy Policy
* [x] Link to TOS

### Privacy Settings
* [x] Record basic log data and use it for improved usability and personal feedback
* [x] Recored my log data and allow anonymised access for researchers
* [x] Share my anonymised log data with others for advanced personal feedback
* [x] Record my log data and use it for reports to teachers and administrators
* [x] Show my profile to other students
* [x] Show my profile to teachers
* [x] Show my profile to the public

## Additional functionality
* [x] Confirmation mail with confirmation link to confirm mail address is missing
* [x] Validate website field

## Check
* [x] On a newly registered account the default profile picture is broken and not set to the default
* [x] after registration creating learning units should be possible (button for new knowledge unit is shown)

**Comment by stylesuxx** [comment]
Can not reproduce the issue with the default profile picture.

**Comment by stylesuxx** [comment]
For testing purposes I suggest getting a teste account with https://ethereal.email/ this can then be added to the config.json in _./server/server/config/config.json_ see example configuration in _./server/server/config/config.example.json_

**Comment by cswertz** [comment]
I did not see the functionality to activate users from the frontend. I expected this in the user management.

**Comment by cswertz** [comment]
If I register myself and upload a picture I never see the picture since the page disappears after clicking "register". It seems necessary to see the picture before actually sending the data.

**Comment by stylesuxx** [comment]
The point is, that I can not show the picture before actually sending the data - the picture is only available for display once it is uploaded, this means, that if I upload the image once the user selects it, that I potentially have an image that does not belong to anyone, should the user abort the registration step.

An alternative I can offer is this: During registration the user has no option to add an image, only when editing his profile. In this case I can upload the image since the user already exists and I can keep track of him.

**Comment by cswertz** [comment]
Funny - I had the same idea this afternoon. So: Great - just removing it seems an easy and satsifying solution. If you touch the form anyway: Is it possible to set the first two options in the data protection settings as turned on by default? That would be perfect - thank you!

**Comment by stylesuxx** [comment]
Sure, I can do that.

**Comment by stylesuxx** [comment]
Adjust registration form and remove non mandatory fields.
