### ISSUE TITLE
Model: User

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#7]

**Comment by stylesuxx** [comment]
@cswertz I updated the *.mwb, added a model and a migration the main changes are

### Unique fields:
* username
* email

### Not NULL:
* id
* username
* email
* password

### Added:
* zip
* country
* updatedAt

### Renamed:
* titlebeforename -> titlePrefix
* titleaftername -> titleSuffix
* date_registration -> createdAt
* privacylevel -> privacyLevel

### Removed:
* preferedlanguage: I would rather do this via a relation to the language table

### Changed:
* picture: this is now a path instead of a blob

The fields that are **not NULL** will also be the required fields. Please adapt this with the other models accordingly, then it will be easier for me to configure the endpoints accordingly.

Please let me know if those changes are OK for you.

**Comment by cswertz** [comment]
In short: Yes.

**Comment by cswertz** [comment]
changed data type for picture to BLOB. changed data type for description to MEDIUMTEXT. changed lastLogin to DATETIME and added it to ERS. Changed createdat and uipdatedat to DATETIME.

**Comment by stylesuxx** [comment]
@cswertz in sequelize Context, Date also includes Time. Sequelize does not have a DATETIME data type you can see the available datatypes here => http://docs.sequelizejs.com/manual/tutorial/models-definition.html#data-types Since in the model it seems to be set to Date again, I assume you fixed this already?

Picture is a path to the user picture on the file system - no need to store binary data in DB.

Also please obey the linting rules, the indentation seems broken at some places. Also at some places there are multiple empty lines.

**Comment by cswertz** [comment]
added privacylevelLog and privacylevelProfile as foreign keys to taxonomies.
