### ISSUE TITLE
Knowledge Units

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#72]
## Check
* [x] Values from taxonomy are shown in first level only. Further levels are missing.
* [ ] EQF - Level is missing
* [x] License was not saved (but was selected)
* [ ] EQF - Level was not saved (could not be selected)
* [ ] ~Object Type was not saved (could not be selected - not necessary aet since only text editor is availabe - but forum might come soon)~ (Not part of this package)

## Change Requests
* [x] During adding or editing a KU the title of the currently active Learning Unit should be shown in the title bar
* [x] order of fields should be reversed (course level etc. on top; objective etc. on bottom)
* [x] "Review" and "Lectorate" should not be shown (is available elsewhere)
* [x] Knowledge Type and media type are mandatory.
* [x] Course level should be renamed to "Level in Course"
* [x] Default for course level should be "intermediate"
* [x] Default for all check boxes should be "yes"
* [x] Default fo Minimum Screen Resoultion should be lowest screen resolution in the list
* [x] Klicking on "Add Knowledge Unit" without filling in anything does not have any effect - obviously the knowledge unit is not saved for some reason. An error message is needed.
* [x] Instead of "Add Text" the Button below the editor should show "save".
* [x] When viewing versions a "done" button is missing to return to the current content.

**Comment by cswertz** [comment]
Adding KU in different Language is not possible yet.

**Comment by stylesuxx** [comment]
EQF Level is missing in the Taxonomies - that's why it is not displayed yet.

**Comment by stylesuxx** [comment]
While adding the title I found a logic error - right now we are attaching knowledge units to learning units - instead we should be attaching them to LearningUnitLanguage. Either that, or a Learning Unit is exclusively only in one language and can not have a relation to a  translation - this is bubbling up now since we did not plan with multi lingo from the beginning. In my opinion this is out of scope, but needs some kind of solution now.

**Comment by cswertz** [comment]
Hello,

> While adding the title I found a logic error - right now we are attaching knowledge units to learning units - instead we should be attaching them to LearningUnitLanguage. Either that, or a Learning Unit is exclusively only in one language and can not have a relation to a translation - this is bubbling up now since we did not plan with multi lingo from the beginning. In my opinion this is out of scope, but needs some kind of solution now.
> The Texts added to a Knowledge Unit again have a language, but technically right now a Learning unit is agnostic of language.

As far as I see multiple languages were considered when we developed the database. For Learning Units: The table "LearningUnit" itself does not contain titles. Those are stored in "LearningUnitLanguage" to allow for translations of the title, as you said. Same for knowledge units - in this case, the language is stored in table "Text" and (for the next package) in "Forum". Reason for that: This way it's possible to translate only part of a knowledge unit (f.i.: do not translate  a video). Flexibility was also the reason for not connecting a certain language version of a knowledge unit to a certain language version of a learning unit. 
But we indeed did not design the authoring process in detail. IMHO the question here is: Should it be possible to create a language version of a knowledge unit without a translation of the title of the corresponding learning unit into that language? I'd say: no. It might make the production processes more flexible - but if authors forget to add the corresponding learning unit title of a certain language at the end, nobody will ever see the knowledge unit in that language.
If you agree, we might add a foreign key from IdLanguage.Texts to LanguageId.LearningUnitLanguage to the existing foreign key from IdLanguage.Texts to Id.Language to express that connection.
Does this sound reasonable?

**Comment by stylesuxx** [comment]
In my opinion it would be a better solution to attach Texts (and for that matter any other upcoming content) to the Title translation of the learning unit itself - this way the content itself could be easily filtered by knowing the language of the Learning unit.

So KnowledgeUnits would reference LearningUnitLanguageId instead of LearningUnitId and we could lose the Language relation within the Texts.

BUT - I am still not sure if we got every relevant case, because I thought, that it might be important to get the localized version of a specific Knowledge unit - as it stands with the suggested changes we could only get the localized version of the Learning Unit.

What do you think @cswertz

**Comment by cswertz** [comment]
Thank's! For the last problem: The metadata in KnowledgeUnit must not be localized - an explanation is an explanation is an explanation. Localization of the word "explanation" (and all  other metadata) is stored as "vocable" in "TaxonomyLanguage". That's where the taxonomy editor should store the words. And that's where the word that is actually shown in the UI should be retrieved from. But that's pretty obvious...
For your first suggestion: As far as I see, that's what I said. Attaching texts (and with the editor, that includes video files and so on) to the language of the learning unit means to attach is to LearningUnitLanguage. That can be expressed by a foreing key to LearningUnitLanguage.LanguageID. 
But you are right: Retrieving a localized content might be expensive - considerably, if we add other content types in the future. On the other hand, the LearningUnitId is stored in KnowledgeUnit and you know the languages from the user profile. So to look up if there is a localized version of a Knowledge Unit and/or to retrieve it is just a left join of KnowledgeUnit and Text. 
But if we add more objectTypes, that might become annoying. I see two options: Either we'll have to go through all objectTypes (if we add more) or add a table KnowledgeUnitLanguages with objectType, LanguageId and KnowledgeUnitId. In the later case, Text does not need LanguageId ant KnowledgeUnit does not need objectType, and Text needs a foreign key to KnowledgeUnitLanguages. As far as I see, the second option is clearer. If this convinces you, I can add the table to the migrations.

**Comment by cswertz** [comment]
@cswertz Add EQF Level to Taxonomy Seeders

**Comment by cswertz** [comment]
@stylesuxx Setting EQF Level is not possible. Entries in the taxonomy are there.

**Comment by stylesuxx** [comment]
EQF levels should now be in taxonomies, double check.

**Comment by stylesuxx** [comment]
Added field
