### ISSUE TITLE
Usability: Eyes or title

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#73]
When editing a learning unit the content (that is: knowledge units) are called by clicking the title.
When editing the taxonomy the content (that is: subtaxonomies) are called by clicking the eye-button.
For me, clicking the text is more intuitive. The eye seems to be more explicit - but this implies "view", not "edit subterms". Maybe a "edit folder" button is available?

**Comment by stylesuxx** [comment]
The taxonomies are edited by clicking the pen icon.
The eye icon is used to view the sub taxonomy - I now changed this icon to be a folder icon and also allow for clicking the taxonomy itself.

**Comment by cswertz** [comment]
Much better. I can not edit the translations of a taxonomy entry, right? I'll add another issue for that and close this one.
