### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#74]
Pictures can not be uploaded into the editor.

**Comment by stylesuxx** [comment]
@cswertz this can be closed now - right? Could you do me a favor and go through the other open issues too and close what is already done in your opinion?

**Comment by cswertz** [comment]
I checked all open issues. For the editor: Images can be uploaded, but the display size of the image can not be adjusted and other  properties of the image can not be set also. I assume the editor allows for that? BTW: Is it possible to upload multimedia files with the editor too? It would be great if sounds and videos can be uploaded too. Can I configure the editor somewhere? What's it's name?

**Comment by cswertz** [comment]
OK. Uploading works. Writing Text beside an image is not possible.

**Comment by stylesuxx** [comment]
Works for me in the editor (not in the display with those, that I have not styled yet.) - we should define which styles we want to have available for images, eg. how they should float, which pre-defined scaling sizes, if any, should be available - I just added the current ones as samples.
Maybe lets have a general discussion about the features we want to have in the editor - there is a custom image builder for the editor, I would suggest we go through that together and configure it accordingly to your needs.

**Comment by cswertz** [comment]
Perfect.
