### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#78]
@cswertz I saw you added a document to the repo. I was thinking, maybe we could have the [docs on google](https://www.google.com/intl/de_at/docs/about/) doc instead? This would allow us to both easily edit/comment them.

git is not the best solution for such binary files, especially tracking changes makes it very difficult. You can see those changes nicely in google docs though.

I would understand though, if you'd prefer to not use google ;-)

**Comment by cswertz** [comment]
All binary files for planning moved to google docs at
https://drive.google.com/drive/folders/0B-VurHfSvlzpQi1mM2ZXQVZYbDg?usp=sharing
