### ISSUE TITLE
Interface: Profile - Set Languages

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#79]
preferred languages can not be set when creating or editing user profile. 
it should be possible to set multiple languages: 

" _________V " (add) 
"__________V" (add) (delete)

The interface should use the first language. Only knowledge units in the languages that are set should be shown to this user. Only the languages set here should be shown as an option when creating knowledge units.

**Comment by stylesuxx** [comment]
This is a topic that I want to put up for discussion again - I think, that it is dangerous to "hide" content in different languages - especially for editors, they would then need to change their prefered language in the profile to see the translations of their content, unless they have set all the available languages as their preferred language - unless this is the case you want it to be, but then I would suggest to limit the language selection when creating new content to only those languages that they have selected.

**Comment by cswertz** [comment]
The last idea is good to improve usability in any case. For the first point: That might be a difference between viewing and editing. When viewing content, showing it in the preferred language makes (and in another language a user added to the profile if the preferred language is not available) probably makes sense. In that case, changing the language is not too difficult anyway since the profile menu is visible all the time.  When editing learning units, the list of available learning units seems to be a starting point an is an issue indeed, since this list will quickly increase to some hundred issues. Filters will be necessary, which is another issue.  For now, I would like to suggest to show the learning units in alphabetic order and without the numbers and than show all available languages for that learning unit behind. The link to editing the knowledge units can be connected to the language. That way, I see all languages but get an implicit filter for the knowledge units. Than, when entering the learning unit, only the content in that language can be shown, but with links to other language versions below. Does this make sense for you?

**Comment by cswertz** [comment]
Well - I did not explain that very clear: 
1) List of learning units with languages behind
2) Click on language
3) show knowledge units with content in that language
4) show language versions of the knowledge units below content.

**Comment by stylesuxx** [comment]
When showing or editing the LU, show ALL available languages, not just the user selected languages.
Do not allow users to edit languages that he has not selected, tell him that he needs to enable this language.

**Comment by stylesuxx** [comment]
The backend now supports adding languages to users. I am not sure what the best way would be to handle the preferred language though.

There are a couple of options that come into mind:
1. The UserLanguage entity has also a "level" field, the preferred language could be the one with the highest level value, but since this can be the same for a couple of languages it is not a good solution.
2. The User gets an additional field that holds his preferred language. This is then a reference to a UserLanguage entity. If the user has no UserLanguage entities set up yet, the preferred language will default to english.

@cswertz what's your opinion?

**Comment by cswertz** [comment]
I think the first solution is good. We have to display stuff in one language. If we can offer multiple languages and the user is able to read multiple languages, we need a selection, like one first preferred language.

**Comment by stylesuxx** [comment]
As discussed in call - we will go with the 2nd variant since it is easier to maintain and more logical. Prefered language will be added to user entity and is referencing one of the userLanguage entities. If no language is set, english is set default

**Comment by cswertz** [comment]
Second solution is better for the frontend. Interface -> User ; Content -> UserLanguages. Dropdown in the profile for preferred language.
