### ISSUE TITLE
Model: Role

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#8]

**Comment by stylesuxx** [comment]
### Renamed:
* role -> slug

### Added:
* name

**Comment by cswertz** [comment]
@stylesuxx: Table "Role" in ERS did not match 00010-Roles.js. I adjusted the ERS: Table renamed to roles, added createdAT, updatedAT.

**Comment by cswertz** [comment]
data type for createdat and updatedat in ORM changed to DATETIME.
