### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#84]
Somewhere between b0da351 and current HEAD (9cd2755) tests stopped working.

**Comment by stylesuxx** [comment]
Breaking change => https://github.com/cswertz/lerndorf/commit/9cd275564477e28f32d88e0cf560fbfe353ab2af

**Comment by cswertz** [comment]
Turned the autoincrement back on. See there.

**Comment by stylesuxx** [comment]
Awesome, thank you - closing this one.
