### ISSUE TITLE
Model: Capability

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#9]

**Comment by stylesuxx** [comment]
### Renamed:
* capability -> slug

### Added:
* name

**Comment by cswertz** [comment]
Capabilities can only be changed trhough the software. Thus update and change do not make much sense here. Deleted from ORM.

**Comment by stylesuxx** [comment]
@cswertz I do not understand this, technically the name/slug could be changed, thus it has the updated field. I can remove created/updated fields if you prefer?

**Comment by cswertz** [comment]
Kept fields, everything fine.
